pipeline {
    agent any

    stages {

        stage('Clone Repo') {
            steps {
                git branch: 'master', url: 'https://github.com/ronitdalal27/VConnect_iDees_CRM_Assessement.git'
            }
        }

        stage('Build JAR') {
            steps {
                sh 'mvn clean package -DskipTests'
            }
        }

        stage('Build Docker Image') {
            steps {
                sh 'docker build -t ronit/dashboard-app:ci .'
            }
        }

        stage('Run Docker Container') {
            steps {
                sh 'docker run -d -p 8080:8080 --name ci-test ronit/dashboard-app:ci'
            }
        }
    }
}
